# Generated by Django 5.0.2 on 2024-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecast',
            name='crew_type',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Director', 'Director'), ('Production', 'Production')], default='Actor', max_length=100),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='crew_name',
            field=models.CharField(blank=True, default='crew1', max_length=100),
        ),
    ]
