# Generated by Django 5.0.2 on 2024-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_moviecast_crew_type_alter_moviecast_crew_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to='video'),
        ),
    ]
